title: 애매하게 이해하면 까먹더라
desciption: Data Engineer로 일하면서 보고 듣고 배운 것들을 정리하고 공유하는 목적을 가진 블로그입니다.

header_pages:
  - index.md
    #  - peter.md
    #  - about.md
    #  - contact.md

style: dark

footer: 'follow me on <a href="https://www.linkedin.com/in/wonseok-yang-de/">linkedin</a>'

# Build settings
remote_theme: b2a3e8/jekyll-theme-console